### ISSUE TITLE
[bug]webpack compile error

### ISSUE THREAD

**Issue by wanghche** [youzan/zent#600]
我在项目中想尝试使用Design component，但是webpack编译报错。

/node_modules/zent/lib/utils/scroll.js:18
var w = window;
        ^
ReferenceError: window is not defined
at Object.<anonymous> (***/node_modules/zent/lib/utils/scroll.js:18:9)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/node_modules/zent/lib/design/preview/DesignPreviewItem.js:37:15)
    at Module._compile (module.js:635:30)

具体代码我就不copy了，只是把示例里的代码简单复制粘贴。

只要
import {Design} from 'zent'
就会报上述错误

**Comment by cpylua** [comment]
你是 SSR？现在 `Design` 这个组件可能还不支持 SSR。

**Comment by wanghche** [comment]
是的，我用的SSR。明白了，谢谢

**Comment by cpylua** [comment]
你可以临时照那个 PR 里的代码修改一下本地 node_modules 里的代码，下个版本发布后就会修复。

**Comment by wanghche** [comment]
好的，谢谢
